"""entries table

Revision ID: 16d2bc180967
Revises: 5231c9838c9f
Create Date: 2020-08-14 02:37:46.437632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d2bc180967'
down_revision = '5231c9838c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.Column('l_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_user_f_name'), 'sub_user', ['f_name'], unique=False)
    op.create_index(op.f('ix_sub_user_l_name'), 'sub_user', ['l_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_user_l_name'), table_name='sub_user')
    op.drop_index(op.f('ix_sub_user_f_name'), table_name='sub_user')
    op.drop_table('sub_user')
    # ### end Alembic commands ###
